export enum Club {
  "D" = "Driver",
  "2W" = "2 Wood",
  "3W" = "3 Wood",
  "4W" = "4 Wood",
  "5W" = "5 Wood",
  "7W" = "7 Wood",
  "9W" = "9 Wood",
  "1H" = "1 Hybrid",
  "2H" = "2 Hybrid",
  "3H" = "3 Hybrid",
  "4H" = "4 Hybrid",
  "5H" = "5 Hybrid",
  "6H" = "6 Hybrid",
  "7H" = "7 Hybrid",
  "2I" = "2 Iron",
  "3I" = "3 Iron",
  "4I" = "4 Iron",
  "5I" = "5 Iron",
  "6I" = "6 Iron",
  "7I" = "7 Iron",
  "8I" = "8 Iron",
  "9I" = "9 Iron",
  "PW" = "Pitching Wedge",
  "GW" = "Gap Wedge",
  "SW" = "Sand Wedge",
  "LW" = "Lob Wedge",
  "HLW" = "High Lob Wedge",
  "P" = "Putter",
}

export const shortClubNames: Record<Club, string> = {
  [Club["D"]]: "Driver",
  [Club["2W"]]: "2 Wood",
  [Club["3W"]]: "3 Wood",
  [Club["4W"]]: "4 Wood",
  [Club["5W"]]: "5 Wood",
  [Club["7W"]]: "7 Wood",
  [Club["9W"]]: "9 Wood",
  [Club["1H"]]: "1 Hybrid",
  [Club["2H"]]: "2 Hybrid",
  [Club["3H"]]: "3 Hybrid",
  [Club["4H"]]: "4 Hybrid",
  [Club["5H"]]: "5 Hybrid",
  [Club["6H"]]: "6 Hybrid",
  [Club["7H"]]: "7 Hybrid",
  [Club["2I"]]: "2 Iron",
  [Club["3I"]]: "3 Iron",
  [Club["4I"]]: "4 Iron",
  [Club["5I"]]: "5 Iron",
  [Club["6I"]]: "6 Iron",
  [Club["7I"]]: "7 Iron",
  [Club["8I"]]: "8 Iron",
  [Club["9I"]]: "9 Iron",
  [Club["PW"]]: "PW",
  [Club["GW"]]: "GW",
  [Club["SW"]]: "SW",
  [Club["LW"]]: "LW",
  [Club["HLW"]]: "HLW",
  [Club["P"]]: "Putter",
};

export const ClubCategories = {
  "Woods/Hybrids": [
    Club.D,
    Club["2W"],
    Club["3W"],
    Club["4W"],
    Club["5W"],
    Club["7W"],
    Club["9W"],
    Club["2H"],
    Club["3H"],
    Club["4H"],
    Club["5H"],
    Club["6H"],
    Club["7H"],
  ],
  Irons: [
    Club["2I"],
    Club["3I"],
    Club["4I"],
    Club["5I"],
    Club["6I"],
    Club["7I"],
    Club["8I"],
    Club["9I"],
  ],
  "Short game": [Club.PW, Club.GW, Club.SW, Club.LW, Club.HLW, Club.P],
};

export const PitchableClubs = [
  Club["7I"],
  Club["8I"],
  Club["9I"],
  Club.PW,
  Club.GW,
  Club.SW,
  Club.LW,
  Club.HLW,
];
