export enum Club {
  "D" = "Driver",
  "1W" = "1 Wood",
  "2W" = "2 Wood",
  "3W" = "3 Wood",
  "4W" = "4 Wood",
  "5W" = "5 Wood",
  "1H" = "1 Hybrid",
  "2H" = "2 Hybrid",
  "3H" = "3 Hybrid",
  "4H" = "4 Hybrid",
  "5H" = "5 Hybrid",
  "1I" = "1 Iron",
  "2I" = "2 Iron",
  "3I" = "3 Iron",
  "4I" = "4 Iron",
  "5I" = "5 Iron",
  "6I" = "6 Iron",
  "7I" = "7 Iron",
  "8I" = "8 Iron",
  "9I" = "9 Iron",
  "PW" = "Pitching Wedge",
  "LW" = "Lob Wedge",
  "SW" = "Sand Wedge",
  "54W" = "54° Wedge",
  "P" = "Putter",
}
