export enum StrokeType {
  FULL = "FULL",
  THREE_QTR = "THREE_QTR",
  PITCH = "PITCH",
  CHIP = "CHIP",
  PUTT = "PUTT",
  FLOP = "FLOP",
  PUNCH = "PUNCH",
  LOW_DRAW = "LOW_DRAW",
  LOW = "LOW",
  LOW_FADE = "LOW_FADE",
  HIGH_DRAW = "HIGH_DRAW",
  HIGH = "HIGH",
  HIGH_FADE = "HIGH_FADE",
  DRAW = "DRAW",
  FADE = "FADE",
  OTHER = "OTHER",
}

// Note, StrokeType enum used to map to the label values, but this would not maintain consistency if the label values were to change.
// The extra mappings here represent the original labels at the time of change to maintain backwards compatibility to older data.
export const StrokeTypeLabels = {
  [StrokeType.FULL]: "Full",
  ["Full"]: "Full",
  [StrokeType.THREE_QTR]: "3/4",
  ["3/4"]: "3/4",
  [StrokeType.PITCH]: "Pitch",
  ["Pitch"]: "Pitch",
  [StrokeType.CHIP]: "Chip",
  ["Chip"]: "Chip",
  [StrokeType.PUTT]: "Putt",
  ["Putt"]: "Putt",
  [StrokeType.FLOP]: "Flop",
  ["Flop"]: "Flop",
  [StrokeType.PUNCH]: "Punch",
  ["Punch"]: "Punch",
  [StrokeType.LOW_DRAW]: "Low Draw",
  [StrokeType.LOW]: "Low",
  [StrokeType.LOW_FADE]: "Low Fade",
  ["Low"]: "Low",
  [StrokeType.HIGH]: "High/Lob",
  ["High/Lob"]: "High/Lob",
  [StrokeType.HIGH_DRAW]: "High Draw",
  [StrokeType.DRAW]: "Draw",
  [StrokeType.HIGH_FADE]: "High Fade",
  ["Draw"]: "Draw",
  [StrokeType.FADE]: "Fade",
  ["Fade"]: "Fade",
  [StrokeType.OTHER]: "Other",
  ["Other"]: "Other",
}
